<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(For your security, we, , ve se_f57ef7</name>
   <tag></tag>
   <elementGuidId>71350896-81b7-4ee2-9a92-2eccafb6284c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;otc-4&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='otc-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8ba3bb6-f2c6-41eb-9d5e-14e9673af7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputid</name>
      <type>Main</type>
      <value>cvf-input-code</value>
      <webElementGuid>93494be4-e6be-46b1-84db-7f9ad75c12c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otc-4</value>
      <webElementGuid>90082b24-dfbc-4752-81a2-01a0039c95bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp-input-box</value>
      <webElementGuid>a8279331-d058-40b9-a763-f187bae039d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>835cd903-8a5b-4e9b-9736-ba256b1497fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>df667920-5b2a-4a5d-add8-921e8afcafe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>caced09b-660b-464f-a8ef-dd1767d3767f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>dfb2f15a-1a75-4303-bcde-16b07fefa601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cvf-input-code&quot;)/span[@class=&quot;a-declarative&quot;]/div[@class=&quot;otp-input-box-container&quot;]/input[@class=&quot;otp-input-box&quot;]</value>
      <webElementGuid>ccf0451f-947e-434b-8ce2-24c454874a21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='otc-4']</value>
      <webElementGuid>765edf9d-02f9-492d-a638-4a2a3b7d21a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cvf-input-code']/span/div/input[4]</value>
      <webElementGuid>ee71a5c6-e14d-4a5d-9dc7-c07d0312048c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[4]</value>
      <webElementGuid>6f2757ff-162f-4a1f-a5e6-9d54604077b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'otc-4' and @type = 'text']</value>
      <webElementGuid>6a9b92dc-e8e5-4c2d-8838-f40183202338</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
