<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(For your security, we, , ve se_eb2a81</name>
   <tag></tag>
   <elementGuidId>8e2b2d78-d124-404b-bb46-223e8fe497e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;otc-5&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='otc-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>600705bf-5c38-45d5-a840-2d37bc01b19c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputid</name>
      <type>Main</type>
      <value>cvf-input-code</value>
      <webElementGuid>56de5a0a-c55e-4639-940a-97faeecba8a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otc-5</value>
      <webElementGuid>1f633d48-88ce-4c18-852d-0452ddac680d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp-input-box</value>
      <webElementGuid>d5c9732b-23dc-43fa-aba9-12d17f52f609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97ca9b8b-0d12-4d0e-b51c-47340b1fa7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>51fde068-b385-4559-ab13-a829d34109a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>5df928a2-1d01-4ef8-9983-794ba423aad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>47f67322-03db-4ea9-ad60-52cd00d5a124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cvf-input-code&quot;)/span[@class=&quot;a-declarative&quot;]/div[@class=&quot;otp-input-box-container&quot;]/input[@class=&quot;otp-input-box&quot;]</value>
      <webElementGuid>ce1780cc-d54a-448d-8d94-44bad04db223</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='otc-5']</value>
      <webElementGuid>ac68ce73-399c-47ce-b7eb-82074137ec26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cvf-input-code']/span/div/input[5]</value>
      <webElementGuid>8500afaa-a81d-4c30-993d-12bfc6be5a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[5]</value>
      <webElementGuid>c1a7e1b2-68c3-4e4d-9d3c-2230a1b88316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'otc-5' and @type = 'text']</value>
      <webElementGuid>0b9aa389-df0a-4987-bbbe-ebb40eb3e941</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
