<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(For your security, we, , ve se_8b21e1</name>
   <tag></tag>
   <elementGuidId>bc4cd79e-711f-4855-a90f-e0db41339d4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;otc-6&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='otc-6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b50f00b1-86dd-4655-9a66-483e181841ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputid</name>
      <type>Main</type>
      <value>cvf-input-code</value>
      <webElementGuid>c567de5c-0ed7-431c-9133-b1a24df0fef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otc-6</value>
      <webElementGuid>8400171a-be4f-435a-9e39-95c9b87cfffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp-input-box</value>
      <webElementGuid>3402501a-fb87-4273-bb1c-80816ec8c3df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bd07ef72-83c3-46a1-a736-eb7c2d810f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c3e8986a-abed-4f69-8c81-e6fd0942e1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>2bb815dc-eac0-4a6d-b23e-9732ab4ba9ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>340cd185-285d-45a3-bfbd-98302ddc278a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cvf-input-code&quot;)/span[@class=&quot;a-declarative&quot;]/div[@class=&quot;otp-input-box-container&quot;]/input[@class=&quot;otp-input-box&quot;]</value>
      <webElementGuid>7752f4dd-520d-4265-9286-5ae4040ce3a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='otc-6']</value>
      <webElementGuid>2fa8e544-168a-44bf-a3e2-a33e12a72577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cvf-input-code']/span/div/input[6]</value>
      <webElementGuid>7c4e1a2a-bdbd-4920-8774-9243825beab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[6]</value>
      <webElementGuid>ac345768-dfdc-41d7-bbe6-c6f3d2d9a4f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'otc-6' and @type = 'text']</value>
      <webElementGuid>794d5b2e-4a7d-4cef-a8c9-12bc0d7fd896</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
